In [1]:
import numpy as np
import pandas as pd
from obspy import read
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import os

In [2]:

# data_directory = './data/lunar/training/data/S12_GradeA/'
# mseed_file = f'{data_directory}{test_filename}.mseed'
mseed_file = '/home/arjun/Desktop/hacking-nasa-with-html/space_apps_2024_seismic_detection/data/mars/training/data/XB.ELYSE.02.BHV.2022-01-02HR04_evid0006.mseed'
st = read(mseed_file)

In [3]:
st[0].stats

         network: XB
         station: ELYSE
        location: 02
         channel: BHV
       starttime: 2022-01-02T04:00:00.025000Z
         endtime: 2022-01-02T04:59:59.975000Z
   sampling_rate: 20.0
           delta: 0.05
            npts: 72000
           calib: 1.0
         _format: MSEED
           mseed: AttribDict({'dataquality': 'D', 'number_of_records': 143, 'encoding': 'FLOAT64', 'byteorder': '>', 'record_length': 4096, 'filesize': 585728})

In [4]:
st.traces[0]

XB.ELYSE.02.BHV | 2022-01-02T04:00:00.025000Z - 2022-01-02T04:59:59.975000Z | 20.0 Hz, 72000 samples

In [5]:
st.traces

[XB.ELYSE.02.BHV | 2022-01-02T04:00:00.025000Z - 2022-01-02T04:59:59.975000Z | 20.0 Hz, 72000 samples]

In [6]:
dir(st)

['__add__',
 '__class__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getslice__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__nonzero__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_cleanup',
 '_dummy_stream_from_string',
 '_get_common_channels_info',
 '_groupby',
 '_ltrim',
 '_merge_checks',
 '_repr_pretty_',
 '_rotate_specific_channels_to_zne',
 '_rotate_to_zne',
 '_rtrim',
 '_trim_common_channels',
 'append',
 'attach_response',
 'clear',
 'copy',
 'count',
 'cutout',
 'decimate',
 'detrend',
 'differentiate',
 'extend',
 'filter',
 'get_gaps',
 'insert',
 'integrate',
 'interpolate',
 'max',
 'merge',
 'normalize',
 'plot',
 'pop',
 'pri

In [7]:
tr = st.traces[0].copy()
tr_times = tr.times()
tr_data = tr.data

# Start time of trace (another way to get the relative arrival time using datetime)
# starttime = tr.stats.starttime.datetime
# arrival = (arrival_time - starttime).total_seconds()
# arrival

In [8]:
tr_times.shape

(72000,)

In [9]:
minfreq = 0.5
maxfreq = 1.0

# Going to create a separate trace for the filter data
st_filt = st.copy()
st_filt.filter('bandpass',freqmin=minfreq,freqmax=maxfreq)
tr_filt = st_filt.traces[0].copy()
tr_times_filt = tr_filt.times()
tr_data_filt = tr_filt.data

In [10]:
from scipy import signal
from matplotlib import cm
f, t, sxx = signal.spectrogram(tr_data_filt, tr_filt.stats.sampling_rate)

In [11]:
f.shape

(129,)

In [12]:
t

array([   6.4,   17.6,   28.8,   40. ,   51.2,   62.4,   73.6,   84.8,
         96. ,  107.2,  118.4,  129.6,  140.8,  152. ,  163.2,  174.4,
        185.6,  196.8,  208. ,  219.2,  230.4,  241.6,  252.8,  264. ,
        275.2,  286.4,  297.6,  308.8,  320. ,  331.2,  342.4,  353.6,
        364.8,  376. ,  387.2,  398.4,  409.6,  420.8,  432. ,  443.2,
        454.4,  465.6,  476.8,  488. ,  499.2,  510.4,  521.6,  532.8,
        544. ,  555.2,  566.4,  577.6,  588.8,  600. ,  611.2,  622.4,
        633.6,  644.8,  656. ,  667.2,  678.4,  689.6,  700.8,  712. ,
        723.2,  734.4,  745.6,  756.8,  768. ,  779.2,  790.4,  801.6,
        812.8,  824. ,  835.2,  846.4,  857.6,  868.8,  880. ,  891.2,
        902.4,  913.6,  924.8,  936. ,  947.2,  958.4,  969.6,  980.8,
        992. , 1003.2, 1014.4, 1025.6, 1036.8, 1048. , 1059.2, 1070.4,
       1081.6, 1092.8, 1104. , 1115.2, 1126.4, 1137.6, 1148.8, 1160. ,
       1171.2, 1182.4, 1193.6, 1204.8, 1216. , 1227.2, 1238.4, 1249.6,
      

In [13]:
sxx.flatten().shape

(41409,)

In [14]:
sxx.shape

(129, 321)

In [15]:
sxx[1].shape

(321,)

In [16]:
import numpy as np
import pandas as pd
from obspy import read
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import os

In [17]:

# data_directory = './data/lunar/training/data/S12_GradeA/'
# mseed_file = f'{data_directory}{test_filename}.mseed'
mseed_file = '/home/arjun/Desktop/hacking-nasa-with-html/space_apps_2024_seismic_detection/data/mars/training/data/XB.ELYSE.02.BHV.2022-01-02HR04_evid0006.mseed'
st = read(mseed_file)

In [18]:
st[0].stats

         network: XB
         station: ELYSE
        location: 02
         channel: BHV
       starttime: 2022-01-02T04:00:00.025000Z
         endtime: 2022-01-02T04:59:59.975000Z
   sampling_rate: 20.0
           delta: 0.05
            npts: 72000
           calib: 1.0
         _format: MSEED
           mseed: AttribDict({'dataquality': 'D', 'number_of_records': 143, 'encoding': 'FLOAT64', 'byteorder': '>', 'record_length': 4096, 'filesize': 585728})

In [19]:
st.traces[0]

XB.ELYSE.02.BHV | 2022-01-02T04:00:00.025000Z - 2022-01-02T04:59:59.975000Z | 20.0 Hz, 72000 samples

In [20]:
st.traces

[XB.ELYSE.02.BHV | 2022-01-02T04:00:00.025000Z - 2022-01-02T04:59:59.975000Z | 20.0 Hz, 72000 samples]

In [21]:
dir(st)

['__add__',
 '__class__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getslice__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__nonzero__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__slotnames__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_cleanup',
 '_dummy_stream_from_string',
 '_get_common_channels_info',
 '_groupby',
 '_ltrim',
 '_merge_checks',
 '_repr_pretty_',
 '_rotate_specific_channels_to_zne',
 '_rotate_to_zne',
 '_rtrim',
 '_trim_common_channels',
 'append',
 'attach_response',
 'clear',
 'copy',
 'count',
 'cutout',
 'decimate',
 'detrend',
 'differentiate',
 'extend',
 'filter',
 'get_gaps',
 'insert',
 'integrate',
 'interpolate',
 'max',
 'merge',
 'normalize',
 'pl

In [22]:
tr = st.traces[0].copy()
tr_times = tr.times()
tr_data = tr.data

# Start time of trace (another way to get the relative arrival time using datetime)
# starttime = tr.stats.starttime.datetime
# arrival = (arrival_time - starttime).total_seconds()
# arrival

In [23]:
minfreq = 0.5
maxfreq = 1.0

# Going to create a separate trace for the filter data
st_filt = st.copy()
st_filt.filter('bandpass',freqmin=minfreq,freqmax=maxfreq)
tr_filt = st_filt.traces[0].copy()
tr_times_filt = tr_filt.times()
tr_data_filt = tr_filt.data

In [24]:
from scipy import signal
from matplotlib import cm
f, t, sxx = signal.spectrogram(tr_data_filt, tr_filt.stats.sampling_rate)

In [30]:
f

array([ 0.      ,  0.078125,  0.15625 ,  0.234375,  0.3125  ,  0.390625,
        0.46875 ,  0.546875,  0.625   ,  0.703125,  0.78125 ,  0.859375,
        0.9375  ,  1.015625,  1.09375 ,  1.171875,  1.25    ,  1.328125,
        1.40625 ,  1.484375,  1.5625  ,  1.640625,  1.71875 ,  1.796875,
        1.875   ,  1.953125,  2.03125 ,  2.109375,  2.1875  ,  2.265625,
        2.34375 ,  2.421875,  2.5     ,  2.578125,  2.65625 ,  2.734375,
        2.8125  ,  2.890625,  2.96875 ,  3.046875,  3.125   ,  3.203125,
        3.28125 ,  3.359375,  3.4375  ,  3.515625,  3.59375 ,  3.671875,
        3.75    ,  3.828125,  3.90625 ,  3.984375,  4.0625  ,  4.140625,
        4.21875 ,  4.296875,  4.375   ,  4.453125,  4.53125 ,  4.609375,
        4.6875  ,  4.765625,  4.84375 ,  4.921875,  5.      ,  5.078125,
        5.15625 ,  5.234375,  5.3125  ,  5.390625,  5.46875 ,  5.546875,
        5.625   ,  5.703125,  5.78125 ,  5.859375,  5.9375  ,  6.015625,
        6.09375 ,  6.171875,  6.25    ,  6.328125, 

In [25]:
f.shape

(129,)

In [26]:
t

array([   6.4,   17.6,   28.8,   40. ,   51.2,   62.4,   73.6,   84.8,
         96. ,  107.2,  118.4,  129.6,  140.8,  152. ,  163.2,  174.4,
        185.6,  196.8,  208. ,  219.2,  230.4,  241.6,  252.8,  264. ,
        275.2,  286.4,  297.6,  308.8,  320. ,  331.2,  342.4,  353.6,
        364.8,  376. ,  387.2,  398.4,  409.6,  420.8,  432. ,  443.2,
        454.4,  465.6,  476.8,  488. ,  499.2,  510.4,  521.6,  532.8,
        544. ,  555.2,  566.4,  577.6,  588.8,  600. ,  611.2,  622.4,
        633.6,  644.8,  656. ,  667.2,  678.4,  689.6,  700.8,  712. ,
        723.2,  734.4,  745.6,  756.8,  768. ,  779.2,  790.4,  801.6,
        812.8,  824. ,  835.2,  846.4,  857.6,  868.8,  880. ,  891.2,
        902.4,  913.6,  924.8,  936. ,  947.2,  958.4,  969.6,  980.8,
        992. , 1003.2, 1014.4, 1025.6, 1036.8, 1048. , 1059.2, 1070.4,
       1081.6, 1092.8, 1104. , 1115.2, 1126.4, 1137.6, 1148.8, 1160. ,
       1171.2, 1182.4, 1193.6, 1204.8, 1216. , 1227.2, 1238.4, 1249.6,
      

In [27]:
sxx.flatten().shape

(41409,)

In [28]:
sxx.shape

(129, 321)

In [29]:
sxx[1].shape

(321,)